default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # adapter: postgresql
  # database: vendelo_development
  # host: localhost
  # port: 5432

  adapter: postgresql
  database: vendelo_development
  username: fbarqueroz
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: vendelo_test

production:
  <<: *default
  database: vendelo_production
  username: vendelo
  password: <%= ENV["VENDELO_DATABASE_PASSWORD"] %>
